[build]
command = "npm --prefix \"project 2\" run build"
publish = "project 2/dist"
functions = "project 2/netlify/functions"
[build.environment]
NODE_VERSION = "18"

[functions]
node_bundler = "nft"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Headers for security and performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
